language: python
dist: xenial
python:
  - "3.6"
install:
  - cp contrib/ini-sample settings.ini
  - pip install -q -r requirements.txt
script:
  - coverage run --source=sgce.core,sgce.accounts,sgce.certificates manage.py test

after_success:
  - coveralls