version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn sgce.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/sgce/web/static
      - media_volume:/home/sgce/web/media
    expose:
      - 8000
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod

  nginx:
    build: ./contrib/nginx
    volumes:
      - static_volume:/home/sgce/web/static
      - media_volume:/home/sgce/web/media
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
